### ISSUE TITLE
Errors after assembly reload

### ISSUE THREAD

**Issue by korchoon** [Seneral/UndoPro#2]
Hi! First of all let me thank you for solving such a pain as unity's Undo system.
But I've got errors after assembly reload.
How to reproduce:
1) Window->SerializableActionTest
2) Create some actions 
3) Create script in the project view (to force assembly reload). Got about 52 errors after deserializing.

Regards, 
Mikhail

**Comment by Seneral** [comment]
Hi! I answered you on the forums because I saw it there first. Best to continue to discuss this problem here though:)
For the record, it seems to be platform specific, for me it works fine using 5.3.6 f1 on Windows 7 and Build target Standalone.
Seneral

**Comment by Seneral** [comment]
Ok, just tested in new 5.4, I indeed get these errors you mentioned there. I'm onto it:)

**Comment by Seneral** [comment]
Apparently it is caused by an overreaction of unity again. Basically they have decided do throw an error when an object's state is checked outside of the main thread, because it is not save. And the Callback OnAfterDesierialize seems to run on a seperate thread.
That means I can't check if a Unity object is null when I'm deserializing. That's garbage.

I'm trying to look for a solution, but checking for null is such a basic operation you should not be forced to try finding a workaround for:/

**Comment by Seneral** [comment]
Just came back to check 5.6, actually I got different errors now that are more like what you described. Can't tell anymore what errors I was getting back then, but the current ones were actually easy to fix:)
So it should work in newer versions now, too.
